### ISSUE TITLE
Mqtt and streamlit in docker

### ISSUE THREAD

**Issue by MauryaShraddha** [robmarkcole/mqtt-camera-streamer#24]
Hello,

I am working on a project which requires to publish the results of some of the programs through mqtt onto the streamlit. However, I have to perform this in docker and I think it's not straight-forward to access webcam through docker. I am getting the following error when I run the camera.py code in docker:
`Traceback (most recent call last):
  File "camero.py", line 50, in <module>
    main()
  File "camero.py", line 28, in main
    client.connect(MQTT_BROKER, port=MQTT_PORT)
  File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused`

Can you please help me resolve this?
Thank you.

**Comment by getcontrol** [comment]
How did you fix this?
